model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm_countloss_newnoise.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l2 
    first_stage_key: density
    cond_stage_key: rgb
    image_size: 64 #  64 -> 128
    channels: 3 # 3-> 1, Gray
    conditioning_key: crossattn
    cond_stage_trainable: false #true

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler # ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ]
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]
        #verbosity_interval: 0
        #warm_up_steps: 1000
        #max_decay_steps: 50000
        #lr_start: 0.001
        #lr_max: 0.1
        #lr_min: 0.0001

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 #64->128  , unused 라는데 << 무슨 의미? 좀 더 조사 필요
        in_channels: 3 # 6->3, Cross Attention후 z 채널, latent space
        out_channels: 3 # z 채널. latent space
        model_channels: 256 # 128
        attention_resolutions:
        - 32 # 32
        - 16 # 16
        - 8 # 8
        num_res_blocks: 2
        channel_mult:
        - 1 # 1 4 8 -> 1 2 4 4
        - 2 
        - 8
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        #unet_trainable: attn

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3 # z 채널
          resolution: 512
          in_channels: 3 # gray
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenClipImageEmbedder # 수정

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6 # 조사 후 변경 원래 12
    num_workers: 5 # 조사 후 변경 
    wrap: False
    train:
      target: ldm.data.shanghai_gaus_PL.ShanghaiTrain
      params:
        size: 256 # 256 -> 512

    validation:
      target: ldm.data.shanghai_gaus_PL.ShanghaiValidation
      params:
        size: 256 # 256->512

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False


  trainer:
    #accelerator: ddp
    #gpus: 1
    benchmark: True